project:
  type: website
  output-dir: docs

website:
  title: "National Parks Scraping Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - href: https://github.com/gunnargriffith/NationalParkAnnualAttendance
        text: GitHub Repo
      - href: Tutorial.md
        text: Package Tutorial

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



